platform :ios, '10.0'

target 'FixedFit' do
  use_frameworks!
	pod 'Firebase/Core'
	pod 'Firebase/Database'
	pod 'Firebase/Auth'
	pod 'Firebase/Storage'
	pod 'ImagePicker'
  target 'FixedFitTests' do
    inherit! :search_paths
  end
end
